# Generated by CMake, DO NOT EDIT

TARGETS:= 
empty:= 
space:= $(empty) $(empty)
spaceplus:= $(empty)\ $(empty)

TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/kiki/dev/slay/build_debug/CMakeFiles/CheckTypeSize/OFF64_T.c))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/kiki/dev/slay/contrib/zlib/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/kiki/dev/slay/contrib/zlib/zconf.h.cmakein))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/kiki/dev/slay/contrib/zlib/zlib.pc.cmakein))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.15.5/share/cmake/Modules/CheckCSourceCompiles.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.15.5/share/cmake/Modules/CheckFunctionExists.c))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.15.5/share/cmake/Modules/CheckFunctionExists.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.15.5/share/cmake/Modules/CheckIncludeFile.c.in))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.15.5/share/cmake/Modules/CheckIncludeFile.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.15.5/share/cmake/Modules/CheckIncludeFileCXX.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.15.5/share/cmake/Modules/CheckTypeSize.c.in))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.15.5/share/cmake/Modules/CheckTypeSize.cmake))

/Users/kiki/dev/slay/build_debug/CMakeFiles/cmake.check_cache: $(TARGETS)
	/usr/local/Cellar/cmake/3.15.5/bin/cmake -H/Users/kiki/dev/slay -B/Users/kiki/dev/slay/build_debug
