# Generated by CMake, DO NOT EDIT

TARGETS:= 
empty:= 
space:= $(empty) $(empty)
spaceplus:= $(empty)\ $(empty)

TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/kiki/dev/slay/src/CMakeLists.txt))

/Users/kiki/dev/slay/build_debug/CMakeFiles/cmake.check_cache: $(TARGETS)
	/usr/local/Cellar/cmake/3.15.5/bin/cmake -H/Users/kiki/dev/slay -B/Users/kiki/dev/slay/build_debug
